name: Sync Docker Hub Overview
on:
  push:
    branches: [ main ]
    paths: [ README.md ]   # or README.DOCKERHUB.md if you use a trimmed file
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}   # e.g., rjsears
            password: ${{ secrets.DOCKERHUB_TOKEN }}       # Hub access token
            repository: rjsears/tftpgui
            short-description: "Full-featured TFTP server (GUI & headless) with Docker support"
            readme-filepath: README.md                     # or README.DOCKERHUB.md
